source 'https://github.com/CocoaPods/Specs.git'

target 'IRLSizeExample' do
    platform :ios, '8.0'
    pod "IRLSize", :path => ".."
end

target 'IRLSizeExample-Watch Extension' do
    platform :watchos, '2.0'
    pod "IRLSize", :path => ".."
end

target 'IRLSizeTests' do
    platform :ios, '8.0'
    pod "IRLSize", :path => ".."
    pod "Kiwi", :inhibit_warnings => true
end
